export default {
  expires: 1523214827000,
  allowRenew: true,
  devices: {
    2: {
      id: 2,
      methods: 19,
      name: 'Dimmer Zwave',
      state: 2,
      statevalue: '',
      type: 'device',
      favorite: true,
    },
    6: {
      id: 6,
      methods: 19,
      name: 'Sovrum Tak',
      state: 2,
      statevalue: '',
      type: 'device',
      favorite: true,
    },
    8: {
      id: 8,
      methods: 19,
      name: 'Vardagsrum Tak',
      state: 2,
      statevalue: '',
      type: 'device',
      favorite: false,
    },
  },
  sensors: {
    1: {
      battery: 254,
      id: 1,
      model: 'temperature',
      name: 'Kylen',
      protocol: 'fineoffset',
      temp: '11.8',
      type: 'sensor',
      favorite: true,
      minMax: { min: { temp: 3.2, updated: 0 }, max: { temp: 14.7, updated: 0 } },
    },
    7: {
      id: 7,
      lum: '2.0',
      model: 'n/a',
      name: 'Multisensor',
      protocol: 'zwave',
      temp: '30.6',
      type: 'sensor',
      favorite: true,
      minMax: { min: { temp: 22.9, updated: 0 }, max: { temp: 37.0, updated: 0 } },
    },
    21: {
      battery: 254,
      humidity: '20',
      id: 21,
      model: 'temperaturehumidity',
      name: 'Tvlåda',
      protocol: 'fineoffset',
      temp: '23.9',
      type: 'sensor',
      favorite: true,
      minMax: { min: { temp: 12.3, updated: 0 }, max: { temp: 27.6, updated: 0 } },
    },
  },
  history: {},
};
